import Image from "next/image";
import Head from "next/head";
import Link from "next/link";
import { Inter } from "next/font/google";
import { motion, AnimatePresence } from "framer-motion";
import Header from "../components/Header";
import Footer from "../components/Footer";
import favicon from "../public/favicon.ico";

const inter = Inter({ subsets: ["latin"] });
const user = {
  name: "5 Cent , 1993",
  desc: "Kraliçe II. Elizabeth",
  imageUrl:
    "https://i.ucoin.net/coin/50/268/50268827-1/australia-5-cents-1993.jpg",
  imageUrl2:
    "https://i.ucoin.net/coin/50/268/50268827-2/australia-5-cents-1993.jpg",
  imageSize: 90,
  denomination: "5 Cent",
  year: "1993",
  description: "Kraliçe II. Elizabeth",
  observe: "https://www.svgrepo.com/show/429644/coin-blank-coin.svg",
  reverse: "https://www.svgrepo.com/show/429644/coin-blank-coin.svg",
};

export async function getStaticProps(context) {
  // fetch the blog posts from the mock API
  // const res = await fetch("http://localhost:3000/api/collection");
  const res = await fetch("https://coin-catalog.vercel.app/api/collection");
  const posts = await res.json();

  // console.log(posts.categories);
  return {
    props: { posts }, // props will be passed to the page
  };
}

export default function Home({ posts }) {
  return (
    <>
      <Head>
        <title>Coin | Next.js 13</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href={favicon.src} type="image/x-icon" />
      </Head>
      <Header/>
      {posts.countries.map((post) => (
        <div className="section">
          <motion.div initial={{ opacity: 0 }} whileInView={{ opacity: 1 }}>
            <div className="bookmarks">
              <p key={post.id}>{post.countryName}</p>
              <>
                {posts.coins.map((p) => {
                  if (p.countryId === post.id) {
                    return (
                      <div className="bookmark">
                        <motion.div
                          whileHover={{
                            scale: 1.2,
                            transition: { duration: 1 },
                          }}
                          whileTap={{ scale: 0.9 }}
                        >
                          <div className="frame">
                            <img
                              className="avatar"
                              src={p.observe ? p.observe : user.reverse}
                              alt={"Photo of " + user.name}
                            />
                          </div>
                        </motion.div>

                        <motion.div
                          whileHover={{
                            scale: 1.2,
                            transition: { duration: 1 },
                          }}
                          whileTap={{ scale: 0.9 }}
                        >
                          <div className="frame">
                            <img
                              className="avatar"
                              src={p.reverse ? p.reverse : user.observe}
                              alt={"Photo of " + user.name}
                            />
                          </div>
                        </motion.div>

                        <div className="information">
                          <h3 key={p.id}>
                            {p.denomination} , {p.year}
                          </h3>
                          <p>{p.description}</p>
                        </div>
                      </div>
                    );
                  }
                })}
              </>
            </div>
          </motion.div>
        </div>
      ))}
     <Footer/>
    </>
  );
}
